# Generated by Django 3.0.8 on 2020-07-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('sido', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('medical', models.IntegerField(blank=True)),
                ('room', models.IntegerField(blank=True)),
                ('tel', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
