# Generated by Django 3.0.8 on 2020-07-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
